config/routes.rb
Rails.application.routes.draw do
 root 'pages#front'
  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/aboutcopy'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'
get 'pages/ux_testing_view'

devise_for :user, :controllers => { registrations: 'registrations' }

 

end

app/models/budget.rb
class Budget < ActiveRecord::Base
	belongs_to :user

	validates :title, presence: true,
			:length => { :minimum => 2, :maximum => 24, :message => "has invalid length"}




end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  
  can_edit_on_the_spot

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    #number f columns excluding created at columns, id and foreign key
    @num_columns = (Budget.column_names.length - 5)
    @column_names_array = Budget.columns.map { |column| column.name }
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end 

  def before_new
    #@chosen_fields = (params[:chosen_fields])
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    @budget.user_id = current_user.id
    #@budget.save

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:title, :money_i_have, :week, :savings, :bills, :lunches, :phone, :travel, :clothing, :activities, :entertainment, :emergency_fund, :chosen_fields)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper

	def bleh
		arr = [[3,4],[5,6]]
		arr.each do |(a,b)|
		  puts "#{a} #{b}"
		  puts a
		end
	end

	def comebacktonameme

		@column_names_array.delete("title")
		@column_names_array.delete("updated_at")
		@column_names_array.delete("created_at")
		@column_names_array.delete("user_id")
		@column_names_array.delete("id")
		return @column_names_array
	end



end

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="fields" style="border: 1px solid black; display: none;">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, id: "titleField" %>
  </div>
  <div class="field">
    <%= f.label :money_i_have %><br>
    <%= f.text_field :money_i_have, id: "money_i_haveField"  %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week, id: "weekField"  %>
  </div>
  <div class="field">
    <%= f.label :savings %><br>
    <%= f.text_field :savings, id: "savingsField"  %>
  </div>
  <div class="field">
    <%= f.label :bills %><br>
    <%= f.text_field :bills, id: "billsField"  %>
  </div>
  <div class="field">
    <%= f.label :lunches %><br>
    <%= f.text_field :lunches, id: "lunchesField" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, id: "phoneField" %>
  </div>
  <div class="field">
    <%= f.label :travel %><br>
    <%= f.text_field :travel, id: "travelField" %>
  </div>
  <div class="field">
    <%= f.label :clothing %><br>
    <%= f.text_field :clothing, id: "clothingField" %>
  </div>
  <div class="field">
    <%= f.label :activities %><br>
    <%= f.text_field :activities, id: "activitiesField" %>
  </div>
  <div class="field">
    <%= f.label :entertainment %><br>
    <%= f.text_field :entertainment, id: "entertainmentField" %>
  </div>
  <div class="field">
    <%= f.label :emergency_fund %><br>
    <%= f.text_field :emergency_fund, id: "emergency_fundField" %>
  </div>
</div>
  <div class="actions">
    <%= image_submit_tag("confirm.png", class: "img img-responsive col-xs-6 col-xs-push-3 col-sm-4 col-md-push-4 col-lg-2 col-lg-push-5 hidden", id: "submitBudgetBtn") %>
  </div>
<% end %>

app/views/budgets/before_new.html.erb
<% stylesheet_link_tag   'dragula'  %>
<%= stylesheet_link_tag   'before_new'  %>

<!-- Ruby variables -->
<% chosen_fields = "none" %>
<br>
<br>
<br>
<br>
<br>
<button href="#" class="btn stickyBtn" onclick="showDragAndDrop();" data-toggle="tooltip" title="Hide or Show the Drag & Drop box"><i id="stickyBtnIcon" class=" fa fa-chevron-down fa-5x" ></i></button>

<div class= "examples" style="margin-left:10px;">
	<button id="helpBtn" type="button" class="btn helpBtn hidden" data-toggle="modal" data-target="#helpModal">
		Help <span class="glyphicon glyphicon-question-sign"></span>
	</button>
	<div class='parent'>
		<h1 style="text-align: center;">What categories are you <u>Budgeting</u> for this week:</h1>
		<ul id='right-defaults' class='col-md-10 col-md-push-1' style="border: 2px dashed #7b69eb; min-height:200px; padding: 10px;"> </ul>
		<div class='wrapper col-md-12'>
			<ul id='left-defaults' assistantHint="Drag these things up to the box" 		class='col-md-12' style=" min-height: 200px;">
			    <li class="taskElement col-xs-6 col-md-4">Savings <%= image_tag "savings", class: "img img-responsive col-md-3" %> </li>
			    <li class="taskElement col-xs-6 col-md-4">Bills <%= image_tag "bills", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4">Lunches <%= image_tag "lunches", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4">Phone <%= image_tag "phone", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4">Travel <%= image_tag "travel", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4">Clothing <%= image_tag "clothing", class: "img img-responsive col-md-3" %></li>
				<li class="taskElement col-xs-6 col-md-4">Activities <%= image_tag "activities", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4">Entertainment <%= image_tag "entertainment", class: "img img-responsive col-md-3" %></li>
			    <li class="taskElement col-xs-6 col-md-4" style="font-size: 2em; line-height: 23px;">Emergency fund <%= image_tag "emergency", class: "img img-responsive col-md-3" %></li>
			    <div class="col-md-12 hidden"><li class="col-md-6 col-md-push-3 whiteFont font600 marginTop20">Make up my own <br><%= image_tag "idea", class: "img img-responsive col-md-2 col-md-push-5 centered" %></li></div>
			</ul>
		</div>  
	</div>
	<button id="continueWithBudgetBtn" class="btn btn-lg greenBG whiteFont" onclick="submitClicked();">Next<arrow>></arrow></button>

  </div>
<!-- list -->
<div id="list">
	<div class="row" style="padding-bottom: 20px; padding-top: 50px;">
		<div class="col-xs-5" style="background-color: #7b69eb; text-align: center;">
			<h2 class="">This budget:</h2>
			<!-- alert shown to user if no items selected -->
			<div class="alert alert-warning listIsEmpty" >
			  <strong> <h3>It looks like you forgot to choose some items to make your budget with</h3></strong>
			  <div id="emptyListMessage" class="row">
			  	<h4>Would you like to to do that now?</h4>
			  	<button type="button" class="btn btn-success col-md-5 col-md-push-1" 
			  			style="margin-right: 5px;" onclick="showDragAndDrop()">Yes</button>
			  	<button type="button" class="btn btn-danger col-md-5 col-md-push-1" data-toggle="modal" data-target=".bs-example-modal-lg">No I don't want to make a budget</button>
			  </div>
			</div>
		</div>
	</div>
	<div class="container" id="prettyList" style="padding-bottom: 50px;"></div>
	<div id="changeSomethingBtn" onclick="showDragAndDrop()">Wait! I want to Change Something</div>
	<div class="col-sm-4">
		<%= link_to new_budget_path(:chosen_fields => chosen_fields), id: "submitBtn", class: "bounce" do %>
			<%= image_tag "next" %>
		<% end %>
	</div>
</div>

<!-- Modal -->
<div id="helpModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Watch How to Create a Budget  -  ( Click to restart it )</h4>
      </div>
      <div class="modal-body">
       	<center><%= image_tag("help_before_new", class: "help_before_new_img",
        :onclick => 'this.src=this.src') %> </center>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default redFont" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag   'before_new'  %>
<%= javascript_include_tag   'dragula'  %>
<%= javascript_include_tag   'example.min'  %>

<!-- the aim is to be able to pass differtnt path/routes to the variables below and dynamically link to them using the partial -->
<% errorMessage = "Are you sure you want to leave this page?"  %>
<% yesPath1 = root_path  %> <!-- not working as inteded yet -->
<% yesPath2 = "Yes I want to got to Y"  %> <!-- not working as inteded yet -->


 <!-- render the Error partial and pass it parameters (column name and its value) -->
 <%= render 'shared/errorModal',  :val1 =>  errorMessage,  :val2 =>  yesPath1,  :val3 =>  yesPath2 %>

<%= render 'shared/assistant',
		:taskMode => true,
		:missedClickMode => false,
		:taskElems =>  ['left-defaults'],
		:pageIntroduce => ['#left-defaults',
							'#right-defaults',
							"To create a budget, drag these things",
							"And then, Bring them up here"
							] %>
		<%# 	troduce params - 1.elm1 to fly to, 2.elm2 to fly to, 3.message1, 4.message2  %>
<style type="text/css">
	/* Extra Small Devices, Phones */ 
	#assistantBubbleHint{
		transform: scale(2);
		position: absolute;
	    top: 150 !important;
	    left: 220!important;
	     background-color: #5d94db;
	}
	@media only screen and (max-width : 992px) {
		#assistantBubbleHint{
			transform: scale(1.6);
			position: absolute;
		    top: 150 !important;
		    left: 180!important;
		    background-color: pink;
		}
	}
	@media only screen and (max-width : 760px) {
		#assistantBubbleHint{
			transform: scale(1.2);
			position: absolute;
		    top: 75 !important;
		    left: 90!important;
		    background-color: yellow;
		}
	}
	
</style>



app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Budgets</h1>

<table>
  <thead>
    <tr>
      <th style="padding-right: 80px;">Created</th>
      <th>Title</th>
      <th>Money in</th>
      <th>Week</th>
      <th>Savings</th>
      <th>Bills</th>
      <th>Lunches</th>
      <th>Phone</th>
      <th>Travel</th>
      <th>Clothing</th>
      <th>Activities</th>
      <th>Entertainment</th>
      <th>Emergency fund</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td style="padding-right: 80px;" >
          <%= budget.created_at.strftime("%d/%h/%Y") %> at
          <%= budget.created_at.strftime("%H:%M") %>  
        </td>
        <td><%= budget.title %> (<%= budget.created_at.strftime("%Y-%m-%d") %>)</td>
        <td><%= budget.money_i_have %></td>
        <td><%= budget.week %></td>
        <td><%= budget.savings %></td>
        <td><%= budget.bills %></td>
        <td><%= budget.lunches %></td>
        <td><%= budget.phone %></td>
        <td><%= budget.travel %></td>
        <td><%= budget.clothing %></td>
        <td><%= budget.activities %></td>
        <td><%= budget.entertainment %></td>
        <td><%= budget.emergency_fund %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<!-- tidy this whole file when finished -->

<%= stylesheet_link_tag "new" %>
<%= javascript_include_tag "http://www.gerardolarios.com/plugins-and-tools/jqmeter/js/jqmeter.min.js" %>
<!-- get the fields that the user wishes to populate -->
<% chosen_fields = params['chosen_fields'] %>
<% chosen_fields_as_array = chosen_fields.gsub(/\s+/m, ' ').strip.split(" ") %>
<script>
// var skiptheweekfield = <%= @user.skiptheweekfield %>;
 //alert("-> " + skiptheweekfield);

  var skipTheWeekField = '<%= @user.skiptheweekfield %>';
  var chosen_fields_as_arrayJS = <%= chosen_fields_as_array.to_json.html_safe %>;
  
      //alert("-> " + skipTheWeekField);
</script>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 id="progressbarMoney_in"></h1>
<div id="myProgress" class="row">
	<div id="myBar" class="col-xs-1" style="background-color: #019875;"> </div>
	<div id="myBar2" class="col-xs-1"> </div>
  <!-- <div id="barEnd" class="col-md-1" style="background-color: #EF4836; float: right; padding: 20px;"> -->
	<!-- <div class="col-md-1 halfCircleRight"></div> -->

	<!-- <div id="barEndText" class="col-md-10"></div>
  </div> -->
  <div class="circlediv" style="max-height: 100%;">
  	<div id="circledivText" class="col-xs-11 col-xs-push-1"></div>
  </div>
</div>  

<div id="wheelContainer"><br><br><br><br>
  <div id="genieQuickButtons" class="ttsOnHover">
    <div class="ttsElem ttsE1">Skip this Question</div>
    <div class="ttsElem ttsE2" onclick="$('#weekNumberHelpAnswer').css('display', 'block');">Help me with this Question</div>
  </div>
  <div id="weekNumberHelpAnswer" class="ttsOnHover col-xs-12">
    <div class="ttsElem ttsE1 weekNumberHelpAnswerBtn1 col-xs-5">This week</div>
    <div class="ttsElem ttsE2 weekNumberHelpAnswerBtn2 col-xs-5 col-xs-push-1">Next week</div>
  </div>
  <div class="weekNumHelper weekNumHelper1"><p>Click this button to skip this question
    <span class="glyphicon glyphicon-remove ignoreThisElem newLineGlyph"> </span>
  </p>
  </div>
  <div class="weekNumHelper weekNumHelper2"><p>Or if you want to answer it, click this button
    <span class="glyphicon glyphicon-ok ignoreThisElem newLineGlyph"> </span>
  </p>
  <div id="weekHelperBtns">
    <div id="weekHelperBtn1" class="col-sm-4 ignoreThisElem">What is this question?</div>
      <h3 id="typingText"></h3>
      <div id="weekHelperBtn2" class="col-sm-4 visHidden ignoreThisElem">Help me with this question</div>
    <div id="weekHelperBtn3" class="col-sm-4 ignoreThisElem">What is a week number?</div>
  </div>
  <span id="closeHelperBtn" class="glyphicon glyphicon-remove ignoreThisElem"></span>
  <span id="closeHelperBtnLeft" class="glyphicon glyphicon-remove ignoreThisElem"></span>
  </div>
<div>
  <h1 id="title" class="pull34percent">Name of Budget</h1>
  <%= image_tag "blank", id: "titleImg_category" %>
</div>
<%= image_tag "nextCategoryArrowGif", class: "nextCategoryArrow hidden" %>
<div id="wheelCycleBtn" class="col-sm-1 hidden"><%= image_tag "rotate", class: "rotateImg img img-responsive" %></div>
<div id="spinWheel" class="spinWheel cursor" >
    <div class="first"><input id="currentField1" type="text" class="rq-form-element"><i></i></div>
    <div class="second blurWheelItem"><input id="currentField3" type="text" ></div>
    <div class="third blurWheelItem"><input id="currentField2" type="text" ></div>
</div>
</div>
<div id="categoriesDock" class="hidden">
<ul class="dock">
  <%= image_tag "geniePoint", id: "genieCategoryShow" %>
  <% firstCat = chosen_fields_as_array[0] %>
  <%= image_tag firstCat.downcase, id: "currentCat" %>
  <!-- set to js var to acces in js file -->
  <script type="text/javascript">
      var categoryArray = <%= raw chosen_fields_as_array %>;
  </script>
  <!-- all but last elem in array -->
  <% chosen_fields_as_array.each_with_index do |cat, index| %>
    <!-- skip first, its already displayed -->
    <% if index > 0 %>
      <li>
        <div title="<%= cat.downcase %>">
          <%= image_tag cat.downcase, class: "#{cat.downcase}_categoryImg catImg" %> 
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

</div>
<%# button_tag "Next", onclick: 'spinWheel();'%>



<div class="recievedParams" style="margin-top: 200px; display: none;"><%= chosen_fields %></div>

<!-- count number of items revieved -->
<div class="hidden numParams">
	<% if chosen_fields %>
		<%= chosen_fields.split.size %>
	<% end %>
</div>

<%= javascript_include_tag "new" %>

<%= render 'form' %>

<style type="text/css">
  #overlay {
    position: fixed; /* Sit on top of the page content */
    display: none; /* Hidden by default */
    width: 100%; /* Full width (cover the whole page) */
    height: 100%; /* Full height (cover the whole page) */
    top: 0; 
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0,0,0,0.5); /* Black background with opacity */
    z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
    cursor: pointer; /* Add a pointer on hover */
}
</style>
<%# link_to 'Back', budgets_path %>

<%= render 'shared/assistant',
    :taskMode => false,
    :missedClickMode => false,
    :taskElems =>  ['spinWheel'],
    :pageIntroduce => ['#title',
                        '#spinWheel div',
                        "This tells you what you have to type",
                        "And then..... put the answer in here",
                        true] %>

          

app/views/budgets/show.html.erb
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/pie.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
<div id="chartdiv">dfdfd</div>

<style>
#chartdiv {
  width: 100%;
  height: 85%;
  margin-top: 10px;
}
g image {
    transform: scale(2);
}

  blockquote{
    border-left:none
}
.quote-badge{
    background-color: rgba(0, 0, 0, 0.2);   
}
.quote-box{
  overflow: hidden;
  border-radius: 17px;
  background-color: #4ADFCC;
  margin-top: -75px;
  margin-left: 60px;
  margin-bottom: 10%;
  color:white;
  box-shadow: 2px 2px 2px 2px #E0E0E0;
  padding-bottom: 25px;
  max-height: 65%;
}

.quotation-mark{
  text-align: center;
    height: 150px;
    font-weight: bold;
    font-size:40px;
    color:white;
    font-family: "Times New Roman", Georgia, Serif;
}

.quote-text{
    margin-top: 0px;
    padding-bottom: 30px;
    font-size: 40px;
    text-align: center;
}

.on_the_spot_editing form{
  font-size: 0.3em;
  color: black;
  background-color: red;
}
.on_the_spot_editing button{
  position: absolute;
}
.editCatItemBtnOk {
    right: 5%;
    bottom: 7%;
}
.editCatItemBtnCancel {
    left: 5%;
    bottom: 7%;
}
/* items with no value */
.itsBlank{background-color: #ff6060; opacity: 0.5;}
.itsBlank:hover{background-color: #46c4b4; opacity: 0.7;}

.budgetDetails{
  position: absolute;
  float: left;
  text-align: center;
}
.budgetDetails h4{
  font-weight: 600;
}
#money_i_have, #weekNum{
  background-color: #7b69eb;
  border-radius: 5px;
  color: white;
  font-size: 1.3em;
      top: 30%;
    left: 15px;
}
#weekNum{
  background-color: #79aafc;
  margin-top: 100px;
}

#categoryEditBubble {
    background-color: orange;
    color: black;
    z-index: 999;
    border: 3px solid black;
    border-radius: 20px;
    font-size: 27pt;
    font-weight: bold;
    position: absolute;
    /* left: 37%; */
    top: 0;
}
.budgetShowImg{
  position: absolute;
  top: 20%;
  right: 39%;
  margin: 10;
}
.activeCard{
  position: absolute;
  right: 2%;
  top: 150%;
  z-index: 90;
}
.animatedStars{
  position: absolute;
  top: 10%;
  right: 8%;
  transform: rotate(42deg);
  z-index: 0;
}
.quote-text span input {
    text-align: center;
    color: #7b69eb !important;
    width: 75% !important;
    border-radius: 50px;
    border-color: orange;
    padding: 17px;
}
.on_the_spot_editing form {
    font-size: 1.5em;
    background-color: #7b69eb;
}
::selection {
  background: orange; /* WebKit/Blink Browsers */
}
.amcharts-chart-div a {
    display: none !important;
}
</style>
<p id="notice"><%= notice %></p>


<!-- excludes nil columns (will exclude created_and other defaults too ) And excludes money_i_have, week  --> 
<!-- <div class="col-md-2" style="background-color: orange;">
  <h5 id="weekNum">This budget is for week: 3</h5>
  <h5>Money I have to spend on this budget: €188</h5>
</div> -->
<div class="col-md-10 col-md-push-2">
   <%# pie_chart @budget.dup.attributes.keep_if{|k,v| 
        !v.nil? && !(k ==  "money_i_have" || k ==  "week" || k ==  "user_id" ) },
        width: "800px",
        height: "400px",
        legend: "bottom" %>
</div>
<div id="editCategoryCards">
  <% @num_columns.times do |budget| %>
  <% col_name = comebacktonameme[budget] %>
    <% col_name %>
    <% if col_name == 'money_i_have' %>
      <div id="money_i_have" class="col-md-2 budgetDetails">
        <%= auto_tts('Money spent on this budget: ') %>
        <h4>€<%= @budget.public_send(col_name) if @budget.respond_to? col_name  %></h4>
      </div>
      <% elsif col_name == 'week' %>
  <!--     <div id="weekNum" class="col-md-2 budgetDetails">
        This budget is for week: 
        <h4><%= @budget.public_send(col_name) if @budget.respond_to? col_name  %></h4>  
      </div> -->
      <% else %>
      <% otherval = @budget.public_send(col_name) if @budget.respond_to? col_name  %>

     
      <% unless [nil, 0].include?(otherval) %>
        <!-- check which ones are not filled in to give it a different css class -->
        <% is_blank =  otherval < 1 ? 'itsBlank' :  'notBlank'  %> 
        <!-- render the partial and pass it parameters (column name and its value) -->
        <%= render 'shared/budget_item',
                :val1 =>  col_name,
                :val2 =>  otherval,
                :val3 =>  is_blank %>
      <% end %>
    <% end %>
  <% end %>
</div>  




<%# link_to 'Edit all at the same time', edit_budget_path(@budget) %> 
<% link_to 'Back', budgets_path %>


<div style="display: none;">
  <div id="categoryEditBubble">Type the new number for <cat>bills</cat> now</div>
</div> 

<%= image_tag "animatedStars", class: "hidden animatedStars" %>

<script>

</script>

<%= javascript_include_tag "showBudget" %>