config/routes.rb
Rails.application.routes.draw do
 root 'pages#front'
  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/aboutcopy'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'
get 'pages/ux_testing_view'

devise_for :user, :controllers => { registrations: 'registrations' }

 

end

app/models/iframe_game.rb
class IframeGame < ActiveRecord::Base
end

app/controllers/iframe_games_controller.rb
class IframeGamesController < ApplicationController
  before_action :set_iframe_game, only: [:show, :edit, :update, :destroy]

  # GET /iframe_games
  # GET /iframe_games.json
  def index
    @iframe_games = IframeGame.all
  end

  # GET /iframe_games/1
  # GET /iframe_games/1.json
  def show
  end

  # GET /iframe_games/new
  def new
    @iframe_game = IframeGame.new
  end

  # GET /iframe_games/1/edit
  def edit
  end

  # POST /iframe_games
  # POST /iframe_games.json
  def create
    @iframe_game = IframeGame.new(iframe_game_params)

    respond_to do |format|
      if @iframe_game.save
        format.html { redirect_to @iframe_game, notice: 'Iframe game was successfully created.' }
        format.json { render :show, status: :created, location: @iframe_game }
      else
        format.html { render :new }
        format.json { render json: @iframe_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iframe_games/1
  # PATCH/PUT /iframe_games/1.json
  def update
    respond_to do |format|
      if @iframe_game.update(iframe_game_params)
        format.html { redirect_to @iframe_game, notice: 'Iframe game was successfully updated.' }
        format.json { render :show, status: :ok, location: @iframe_game }
      else
        format.html { render :edit }
        format.json { render json: @iframe_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iframe_games/1
  # DELETE /iframe_games/1.json
  def destroy
    @iframe_game.destroy
    respond_to do |format|
      format.html { redirect_to iframe_games_url, notice: 'Iframe game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iframe_game
      @iframe_game = IframeGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iframe_game_params
      params.require(:iframe_game).permit(:link, :title)
    end
end

app/helpers/iframe_games_helper.rb
module IframeGamesHelper
end

app/views/iframe_games/_form.html.erb
<%= form_for(@iframe_game) do |f| %>
  <% if @iframe_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iframe_game.errors.count, "error") %> prohibited this iframe_game from being saved:</h2>

      <ul>
      <% @iframe_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iframe_games/edit.html.erb
<h1>Editing Iframe Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @iframe_game %> |
<%= link_to 'Back', iframe_games_path %>

app/views/iframe_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Iframe Games</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iframe_games.each do |iframe_game| %>
      <tr>
        <td><%= iframe_game.link %></td>
        <td><%= link_to 'Show', iframe_game %></td>
        <td><%= link_to 'Edit', edit_iframe_game_path(iframe_game) %></td>
        <td><%= link_to 'Destroy', iframe_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iframe game', new_iframe_game_path %>

app/views/iframe_games/new.html.erb
<h1>New Iframe Game</h1>

<%= render 'form' %>

<%= link_to 'Back', iframe_games_path %>

app/views/iframe_games/show.html.erb
<style type="text/css">
    body, html
    {
        margin: 0; padding: 0; height: 100%; overflow: hidden;
    }

    #content
    {
        position:absolute; left: 0; right: 0; bottom: 0; top: -320px; 
    }

	#floating-button{
	  width: 355px;
	  height: 55px;
	  border-radius: 50%;
	  background: #db4437;
	  position: fixed;
	  bottom: 30px;
	  left: 30px;
	  cursor: pointer;
	  box-shadow: 0px 2px 5px #666;
	}

	.plus{
	  color: white;
	  position: absolute;
	  top: 0;
	  display: block;
	  bottom: 0;
	  left: 0;
	  right: 0;
	  text-align: center;
	  padding: 0;
	  margin: 0;
	  line-height: 55px;
	  font-size: 38px;
	  font-family: 'Roboto';
	  font-weight: 300;
	  animation: plus-out 0.3s;
	  transition: all 0.3s;
	}
	.plus a{
		color: white;
	}

	#container-floating{
	  position: fixed;
	  width: 100%;
	  height: 70px;
	  bottom: 30px;
	  right: 30px;
	  z-index: 50px;
	  background-color: #7b69eb;
	}
</style>
	<div id="content">
		<iframe width="100%" height="80%" frameborder="0" src="<%= @iframe_game.link %>" />
	</iframe>
	</div>

	<div id="container-floating">
	  <div id="floating-button" data-toggle="tooltip" data-placement="left" data-original-title="Create" onclick="newmail()">
		<p class="plus"><i class="fa fa-arrow-left" aria-hidden="true"></i> <a href="/pages/store">Leave This Game </a> </p>
	  </div>
	</div>