config/routes.rb
Rails.application.routes.draw do
 root 'pages#front'
  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/aboutcopy'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'
get 'pages/ux_testing_view'

devise_for :user, :controllers => { registrations: 'registrations' }

 

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :link, :icon, :category)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<%= stylesheet_link_tag "patternlock", :cache => true %>
<%= javascript_include_tag "patternlock", :cache => true %>


<%= stylesheet_link_tag "videos" %>
<!-- <h1 id="title">Videos</h1>
<div class="container">
  <div id="videoContainer" class="row mar-top-30">
    <% @videos.each do |video| %>
    <!- video item --
      <div class="col-sm-6 videoElm">
          <div id="testBox" class="box text-center">
            <div class="video hidden">
              <iframe src="<%= video.link %>?version=3&enablejsapi=1" class="testVidClass" heightframeborder="0" allowfullscreen></iframe>
            </div>
            <div class="videoDescCard">
                <div class="incon-box">
                    <i class="fa <%= video.icon %>" aria-hidden="true"></i>
                </div>
                <h3 class="box-tittle"><%= video.title %> </h3>
                <p class="box-text"><%= video.description %></p>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>
-->
<% link_to 'New Video', new_video_path %>

<%= stylesheet_link_tag "filterPanelReset" %>
<%= stylesheet_link_tag "filterPanelStyle" %>
<!-- Modernizr here -->
    



<!--
<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">

<ul id="myUL">
  <li><a href="#">Adele</a></li>
  <li><a href="#">Agnes</a></li>

  <li><a href="#">Billy</a></li>
  <li><a href="#">Bob</a></li>

  <li><a href="#">Calvin</a></li>
  <li><a href="#">Christina</a></li>
  <li><a href="#">Cindy</a></li>
</ul>
-->
<header class="cd-header">
  <br><br>
    <h1>Videos</h1>
  </header>

  <main id="filterPanelContainer" class="cd-main-content">
    <div class="cd-tab-filter-wrapper">
      <div class="cd-tab-filter">
        <ul class="cd-filters">
          <li class="placeholder"> 
            <a data-type="all" href="#0">All</a> <!-- selected option on mobile -->
          </li> 
          <li class="filter"><a class="selected" href="#0" data-type="all">All</a></li>
          <li class="filter" data-filter=".category-money"><a href="#0" data-type="category-money">Money</a></li>
          <li class="filter" data-filter=".category-budgets"><a href="#0" data-type="category-budgets">Budgets</a></li>
        </ul> <!-- cd-filters -->
      </div> <!-- cd-tab-filter -->
    </div> <!-- cd-tab-filter-wrapper -->

    <section class="cd-gallery">
      <ul>
        <!-- <li class="mix category-money check1 radio2 option3"><img src="" alt="Image 1"></li>
        <li class="mix category-budgets check2 radio2 option2"><img src="" alt="Image 2"></li>
 -->
        <% @videos.each do |video| %>
    <!-- video item -->
    
      <li class="col-sm-6 videoElm mix category-<%= video.category %>">
          <div id="testBox" class="box text-center">
            <div class="video hidden">
              <iframe src="<%= video.link %>?version=3&enablejsapi=1" class="testVidClass" heightframeborder="0" allowfullscreen></iframe>
            </div>
            <div class="videoDescCard">
                <div class="incon-box">
                    <i class="fa <%= video.icon %>" aria-hidden="true"></i>
                </div>
                <h3 class="box-tittle"><%= video.title %> </h3>
                <p class="box-text"><%= video.description %></p>
            </div>
          </div>
      </li>
    
    <% end %>
     <!--    <li class="mix category-money check3 radio3 option1"><img src="" alt="Image 3"></li>
        <li class="mix category-money check3 radio2 option4"><img src="" alt="Image 4"></li>
        <li class="mix category-money check1 radio3 option2"><img src="" alt="Image 5"></li>
        <li class="mix category-budgets check2 radio3 option3"><img src="" alt="Image 6"></li>
        <li class="mix category-budgets check2 radio2 option1"><img src="" alt="Image 7"></li>
        <li class="mix category-money check1 radio3 option4"><img src="" alt="Image 8"></li>
        <li class="mix category-budgets check1 radio2 option3"><img src="" alt="Image 9"></li>
        <li class="mix category-money check3 radio2 option4"><img src="" alt="Image 10"></li>
        <li class="mix category-money check3 radio3 option2"><img src="" alt="Image 11"></li>
        <li class="mix category-budgets check1 radio3 option1"><img src="" alt="Image 12"></li> -->
        <li class="gap"></li>
        <li class="gap"></li>
        <li class="gap"></li>
      </ul>
      <div class="cd-fail-message">No results found</div>
    </section> <!-- cd-gallery -->

    <div class="cd-filter">
      <form>
        <div class="cd-filter-block">
          <h4>Check boxes</h4>

          <ul class="cd-filter-content cd-filters list">
            <li>
              <input class="filter" data-filter=".check1" type="checkbox" id="checkbox1">
                <label class="checkbox-label" for="checkbox1">Money</label>
            </li>

            <li>
              <input class="filter" data-filter=".check2" type="checkbox" id="checkbox2">
              <label class="checkbox-label" for="checkbox2">Budgets</label>
            </li>

            <li>
              <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
              <label class="checkbox-label" for="checkbox3">Option 3 here</label>
            </li>
          </ul> <!-- cd-filter-content -->
        </div> <!-- cd-filter-block -->

        <div class="cd-filter-block">
          <h4>Select</h4>
          
          <div class="cd-filter-content">
            <div class="cd-select cd-filters">
              <select class="filter" name="selectThis" id="selectThis">
                <option value="">Choose an option</option>
                <option value=".option1">Option 1</option>
                <option value=".option2">Option 2</option>
                <option value=".option3">Option 3</option>
                <option value=".option4">Option 4</option>
              </select>
            </div> <!-- cd-select -->
          </div> <!-- cd-filter-content -->
        </div> <!-- cd-filter-block -->
      </form>

      <a href="#0" class="cd-close">Close</a>
    </div> <!-- cd-filter -->

   <!-- keep for app store  <a href="#0" class="cd-filter-trigger">Filters</a> -->
  </main> <!-- cd-main-content -->




<script>
  $(document).ready( function() {
    //click on the video div to show video(iframe)
    $('.box').on('click', function(){
      $(this).closest('div').children(".video").toggleClass('hidden');
    });
  });

  function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("videoContainer");
    li = ul.getElementsByClassName("videoElm");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("h3")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script>

<%= javascript_include_tag "jquery.mixitup.min" %>
<%= javascript_include_tag "filterPanelMain" %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @video.link %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @video.icon %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>