config/routes.rb
Rails.application.routes.draw do
 root 'pages#front'
  resources :iframe_games
  resources :videos
get 'budgets/before_new'

resources :budgets do
  collection do
    put :update_attribute_on_the_spot
    get :get_attribute_on_the_spot
  end
end

get 'pages/home'
get 'pages/about'
get 'pages/aboutcopy'
get 'pages/front'
get 'pages/profile'
get 'pages/store'
get 'pages/calculator'
get 'pages/ux_testing_view'

devise_for :user, :controllers => { registrations: 'registrations' }

 

end

app/views/pages/_header.html.erb
<style type="text/css">
  .navbar-default{
    border: 3px solid #7b69eb;
    border-radius: 15px;
    width: 98%;
    margin-left: 1%;
    margin-top: 1.8%;
    background-color: #8b7aecad;
    font-weight: bold;
    transform: scaleY(1.5);
    letter-spacing: 1px;
  }

  .navbar-default .navbar-nav > li > a:focus, .navbar-default .navbar-nav > li > a:hover{
        background-color: transparent;
    text-decoration: overline;
    font-size: 1.3em;
        color: #ffb471;
    font-weight: bolder;
  }

  .navbar-default .navbar-nav > .active > a{
    background-color: rgba(245, 245, 245, 0.5);
  }
  .navbar-default .navbar-nav > .active > a:hover{
    background: none;
  }
  .navbar-default .navbar-nav > li > a {
    color: white;
}
.navbar-nav{
  margin-left: -10%;
}


.navbar-brand b{
  color: #030006fa;
    font-weight: 900;
    margin-left: -150px;
    padding-right: 100px;
}
</style>
<div id="navigation" class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="color: #7b69eb;" href="/"><b><%= auto_tts('My Money Counts') %></b></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %> ttsOnHover"><a href="/" class="smothscroll"><%= auto_tts('About the app') %></a></li>
        <% if !user_signed_in? %>
              <li class="ttsOnHover <%= 'active' if current_page?(new_user_session_path) %>"> <%= link_to(new_user_session_path)  do %> 
                <%= auto_tts('Login') %>
                  <% end %>
                </li>
              <li class="ttsOnHover <%= 'active' if current_page?(new_user_registration_path) %>"> 
                <%= link_to( new_user_registration_path) do %>
                  <%= auto_tts('Sign up') %>
                <% end %>
                </li>    
        <% else %>
               <li class="ttsOnHover <%= 'active' if current_page?(pages_profile_path) %>"><a href="/pages/profile"><%= auto_tts('My Profile') %></a></li>
              <!-- <li><a href="/pages/profile">My Budgets</a></li> -->
              <li class="ttsOnHover <%= 'active' if current_page?(budgets_before_new_path) %>"><a href="/budgets/before_new"><%= auto_tts('Create a Budget now') %></a></li>    
          </ul>
          <ul class="nav navbar-nav" style="float: right;">
              <li class="ttsOnHover <%= 'active' if current_page?(pages_store_path) %>"><a href="/pages/store"><%= auto_tts('App store') %></a></li> 
              <li class="ttsOnHover <%= 'active' if current_page?(pages_calculator_path) %>"><%= link_to pages_calculator_path do %>
                <%= auto_tts('Calculator') %>
              <% end %> </li>
              <li class="ttsOnHover <%= 'active' if current_page?(videos_path) %>"><%= link_to videos_path do %> 
                  <%= auto_tts('Videos') %>
                <% end %></li>
              <li ><%= link_to(destroy_user_session_path) do %>
                  <%= auto_tts('Logout') %>
                <% end %>
              </li>   
          </ul>
        <% end %>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/pages/about.html.erb
<!-- render the assistant partial and pass it parameters (column name and its value) -->
<%= render 'shared/assistant',  :val1 =>  'fffffff2' %>

app/views/pages/aboutcopy.html.erb
<%= render 'shared/pattern_unlock2' %>

app/views/pages/calculator.html.erb
<%= stylesheet_link_tag "calculator" %>
<!-- change this minus business! -->
<div style="margin-top: 9%;">
	<div class="col-md-6 typeOfCalcBtn numberCalcBtn" style="background-color: #78CBC3;">
		<h1>Number calculator</h1>
	</div>
	<div class="col-md-6 typeOfCalcBtn moneyCalcBtn" style="background-color: #7b69eb;">
		<h1>Money calculator</h1>
	</div>	
	<!-- arrows that indicate which calculator is active -->
	<div id="arrow1" class="col-md-6 typeOfCalcBtnArrow" style="color: #78CBC3; visibility: hidden;">
		<i class="fa fa-caret-down"></i>
	</div>
	<div id="arrow2" class="col-md-6 typeOfCalcBtnArrow" style="color: #7b69eb;">
		<i class="fa fa-caret-down"></i>
	</div>	

	<div class="col-md-12 calculatorMain" style="background-color: #7b69eb;">
		<!-- number calculator -->
		 <div id="calculator_number" class="col-md-6 col-md-push-3 calculator hidden">
	        <div id="" class="result"></div>
	        <span class="key col-md-3" value='7'>7</span>
	        <span class="key col-md-3" value='8'>8</span>
	        <span class="key col-md-3" value='9'>9</span>
	        <span class="key clear-key right-key col-md-3" value='C'>
	        	<%= image_tag "backspace", style: "height: 5%;" %>
	        </span>
	        <span class="key col-md-3" value='4'>4</span>
	        <span class="key col-md-3" value='5'>5</span>
	        <span class="key col-md-3" value='6'>6</span>
	        <span class="key right-key col-md-3 opHidden" value='/'>/</span>
	        <span class="key col-md-3" value='1'>1</span>
	        <span class="key col-md-3" value='2'>2</span>
	        <span class="key col-md-3" value='3'>3</span>
	        <span class="key right-key col-md-3" value='+'><h3>+</h3></span>
	        <span class="key col-md-3 bottomKey" value='0'>0</span>
	        <span class="key col-md-3 bottomKey" value='00'>00</span>
	        <span class="key col-md-3 bottomKey" value='.'><dot>.</dot></span>
	        <span class="key right-key col-md-3 opHidden" value='*'>*</span>
	        <span class="key equal-key col-md-3" value='='>=</span>
	        <span class="key right-key col-md-3 hidden" value='-'>-</span>
	    </div>
	    <!-- money calculator -->
	    <div id="calculator_money" class="col-md-6 col-md-push-3 calculator" style="">
	    	<div id="" class="result"></div>
	        <span class="key key-money col-md-3" value='100'>
	        	<%= image_tag "euroCurrency/100e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='50'>
	        	<%= image_tag "euroCurrency/50e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='20'>
	        	<%= image_tag "euroCurrency/20e", class: " img img-responsive" %>
	      	</span>
	        <span class="key clear-key right-key col-md-3 marginB20" value='C'>
	        	<%= image_tag "backspace" %>
	        </span>
	        <span class="key key-money col-md-3" value='10'>
	        	<%= image_tag "euroCurrency/10e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='5'>
	        	<%= image_tag "euroCurrency/5e", class: " img img-responsive" %>
	      	</span>
	        <span class="key key-money col-md-3" value='2'>
	        	<%= image_tag "euroCurrency/2e", class: " img img-responsive coinBtn" %>
	      	</span>
	        <span class="key right-key col-md-3 opHidden marginB20" value='/'>/</span>
	        <span class="key key-money col-md-3" value='1'>
	        	<%= image_tag "euroCurrency/1e", class: " img img-responsive coinBtn" %>
	        </span>
	         <span class="key key-money col-md-3" value='.50'>
	        	<%= image_tag "euroCurrency/50c", class: " img img-responsive coinBtn" %>
	        </span>
	        <span class="key key-money col-md-3" value='.20'>
	        	<%= image_tag "euroCurrency/20c", class: " img img-responsive coinBtn" %>
	        </span>
	        <span class="key right-key col-md-3 marginB20" value='+'><h3>+</h3></span>
	        <span class="key key-money col-md-3" value='.10'>
	        	<%= image_tag "euroCurrency/10c", class: " img img-responsive coinBtn" %>
	        </span>
	        <span class="key key-money col-md-3" value='.5'>
	        	<%= image_tag "euroCurrency/5c", class: " img img-responsive coinBtn" %>
	        </span>
	        <span class="key key-money col-md-3" value='.'><dot>.</dot></span>
	        <span class="key right-key col-md-3 opHidden marginB20" value='*'>X</span>
	        <span class="key equal-key col-md-3" value='='>=</span>
	        <span class="key right-key col-md-3 hidden" value='-'>-</span>
	    </div>
	</div>
</div>

<%= javascript_include_tag "calculator" %>

app/views/pages/front.html.erb
<%= stylesheet_link_tag "theme" %>
	<section id="home" name="home" style="margin-top: -40px;"></section>
	<div id="headerwrap">
	    <div class="container">
	    	<div class="row centered">
	    		<div class="col-lg-12">
					<h1>Welcome To <b>My Money Counts</b></h1>
					<h3>Helping you to better manage your money</h3>
					<br>
	    		</div>
	    		<div class="col-lg-2">
	    			<h5 id="heroTitle1"><center>Manage your money</center></h5>
	    			<p>Put a budget together in no time using the Drag & Drop budget maker.</p>
	    			<%= image_tag("arrow1", class: "hidden-xs hidden-sm hidden-md") %>
	    		</div>
	    		<div class="col-lg-8">
	    			<%= image_tag("app-bg2", class: "img-responsive mainBg") %>
	    		</div>
	    		<div class="col-lg-2">
	    			<br>
	    			<br>
	    			<br>
	    			<h5>Clearly see where your money goes</h5>
	    			<%= image_tag("arrow2", class: "hidden-xs hidden-sm hidden-md") %>
	    			<!-- <p>Clearly see where your money is going via your dashboard visuals</p> -->
	    			<div style="margin-top: 175px;">
		    			<%= image_tag("plusMore", class: "hidden-xs hidden-sm hidden-md ") %>
		    			<h5 class="andMoreText"> And More!</h5>
	    			</div>
	    		</div>
	    	</div>
	    </div> <!--/ .container -->
	</div><!--/ #headerwrap -->

	<section id="desc" name="desc"></section>
	<!-- INTRO WRAP -->
	<div id="intro">
		<div class="container">
			<div class="row centered">
				<h1>The basics provided by My Money Counts</h1>
				<br>
				<br>
				<div class="col-lg-4">
					<%= image_tag("intro015") %>
					<h3>See where your money goes</h3>
					<p>Visualize your spending habits so you know exactly what's going in, and out.</p>
				</div>
				<div class="col-lg-4">
					<%= image_tag("intro02") %>
					<h3>Get ahead</h3>
					<p>Create budgets for the comming weeks. You can even access old budgets too!</p>
				</div>
				<div class="col-lg-4">
					<%= image_tag("intro032") %>
					<h3>Access Anywhere</h3>
					<p>Use and interact with My Money Counts anywhere using any device.</p>
				</div>
			</div>
			<br>
			<hr>
	    </div> <!--/ .container -->
	</div><!--/ #introwrap -->
	
	<!-- FEATURES WRAP -->
	<div id="features">
		<div class="container">
			<div class="row">
				<h1 class="centered">What can I do with My Money Counts?</h1>
				<br>
				<br>
				<div class="col-lg-6 centered">
					<%= image_tag("mobile",  class: "centered", id: "showFeaturesPhone1") %>
					<%= image_tag("mobile2", class: "hidden centered", id: "showFeaturesPhone2") %>
					<%= image_tag("mobile4", class: "hidden centered", id: "showFeaturesPhone4") %>
				</div>
				
				<div class="col-lg-6">
					<h3>Some Features</h3>
					<br>
				<!-- ACCORDION -->
		            <div class="accordion ac" id="accordion2">
		                <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_1 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
		                        Interactive & Effortless Budget Creation
		                        </a>
		                    </div><!-- /accordion-heading -->
		                    <div id="collapseOne" class="accordion-body collapse in">
		                        <div class="accordion-inner">
								<p>A series of tools are availible at the users disposal which ensure a pleasant experience. These tools make Budget creation as simple as it should be. These tools are designed around UX research techniques - and will soon be tested by My Money Counts users to better improve theme.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		
		                <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_2 accordion-toggle" data-toggle="collapse"
		                           data-parent="#accordion2" href="#collapseTwo">
		                           Input Wheel
		                        </a>
		                    </div>
		                    <div id="collapseTwo" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>Nobody likes filling out long forms, paper or digital. The process is repetitive and unpleasant - clicking into the field, reading the title and inputting the appropriate answer before continuing to move to the next field. Rinse & Repeat untill the form is completed. This is how it is done on every website & app. <br><br> When answers are required from My Money Counts users, whether it be for creating a Budget or signing up, an interactive wheel can be used. This wheel brings the field to the user each time, no messing, no wasted efferts or time. Cut out the confussion.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		
		                 <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_3 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
		                        Drag & Drop 
		                        </a>
		                    </div>
		                    <div id="collapseThree" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>Before a user even fills out a form stating how much they will spend on certain things, first they need to choose what items they will be (rent, going out for dinner, savings etc.) This is another time when the user is prompted for answers. <br> <br> A drag and drop feature is displayed to the user prior to the wheel where they can drag items of their choosing into a box and make a budget depending on these items. Not every budget is the same so having this level of cusomization mixed with its ease of use is a useful solution.</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>
		                
		                 <div class="accordion-group">
		                    <div class="accordion-heading">
		                        <a class="showFeatures_4 accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
		                        Visualizations
		                        </a>
		                    </div>
		                    <div id="collapseFour" class="accordion-body collapse">
		                        <div class="accordion-inner">
								<p>When the user creates a budget they can view how their money is being spent using the visual aid(pie chart) provided. This way their spendings can be seen in proportions relative to one another. <br> <br>Its one way to find out you spend nearly as much on junk food as you do rent!</p>
								</div><!-- /accordion-inner -->
		                    </div><!-- /collapse -->
		                </div><!-- /accordion-group -->
		                <br>			
					</div><!-- Accordion -->
				</div>
			</div>
		</div><!--/ .container -->
	</div><!--/ #features -->
	
	<section id="showcase" name="showcase"></section>
	<div id="showcase">
		<div class="container">
			<div class="row">
				<h1 class="centered">Some Screenshots</h1>
				<br>
				<div class="col-lg-8 col-lg-offset-2">
					<div id="carousel-example-generic" class="carousel slide">
					  <!-- Indicators -->
					  <ol class="carousel-indicators">
					    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
					  </ol>
					  <!-- Wrapper for slides -->
					  <div class="carousel-inner">
					    <div class="item active">
					      <%= image_tag("item-011") %>
					    </div>
					    <div class="item">
					      <%= image_tag("item-022") %>
					    </div>
					    <div class="item">
					      <%= image_tag("item-3") %>
					    </div>
					  </div>
					</div>
				</div>
			</div>
			<br><br><br>	
		</div><!-- /container -->
	</div>	

	<section id="contact" name="contact"></section>
	<div id="footerwrap" style="display: none;">
		<div class="container">
			<div class="col-lg-5">
				<h3>Address</h3>
				<p>
				Av. Greenville 987,<br/>
				New York,<br/>
				90873<br/>
				United States
				</p>
			</div>
			<div class="col-lg-7">
				<h3>Drop Us A Line</h3>
				<br>
				<form role="form" action="#" method="post" enctype="plain"> 
				  <div class="form-group">
				    <label for="name1">Your Name</label>
				    <input type="name" name="Name" class="form-control" id="name1" placeholder="Your Name">
				  </div>
				  <div class="form-group">
				    <label for="email1">Email address</label>
				    <input type="email" name="Mail" class="form-control" id="email1" placeholder="Enter email">
				  </div>
				  <div class="form-group">
				  	<label>Your Text</label>
				  	<textarea class="form-control" name="Message" rows="3"></textarea>
				  </div>
				  <br>
				  <button type="submit" class="btn btn-large btn-success">SUBMIT</button>
				</form>
			</div>
		</div>
	</div>
	<div id="c">
		<div class="container">
			<p>Maybe add some Links Here for<a href="http://www.blacktie.co">Budget creation & profile</a></p>
		</div>
	</div>

	<script>
		$('.carousel').carousel({
		  interval: 4000
		})

		$( ".showFeatures_2" ).click(function() {
	        //change image with class showFeaturesPhone to mobile2
	        $("#showFeaturesPhone1").addClass("hidden");
	        $("#showFeaturesPhone2").removeClass("hidden");
	    });

	    $( ".showFeatures_4" ).click(function() {
	        //change image with class showFeaturesPhone to mobile2
	        $("#showFeaturesPhone2").addClass("hidden");
	        $("#showFeaturesPhone4").removeClass("hidden");
	    });
	</script>

app/views/pages/profile.html.erb
<%= stylesheet_link_tag "profile" %>
<br><br><br><br><br><br>
<% if !user_signed_in? %>
	You are not Logged in yet. <br><br>
	<%= link_to('Login here', new_user_session_path)  %>  
<% else %>
	 <h1 class="profile_header">Your Profile</h1> 
<% end %>

<% @users_budgets.each do |o| %>
	<!-- <div style="border: 1px solid black"><%= o.title %></div>-->
<% end  %>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-8 col-sm-push-1 col-md-push-2">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-xs-5 col-sm-4 imgContainer">
                        <% if  @user.profileimage.present? %>
                           <%=image_tag (@user.profileimage), class: "img-rounded img-responsive" %>
                        <% else %>
                            <%= image_tag 'profileDefault'%>
                        <% end %>
                    </div>
                    <div class="col-sm-7">
                        <h4 class="profile_name col-sm-8"><%= @user.first_name %> <%= @user.last_name %></h4> 
                        <%# button_tag "Change This", id: "chnageThisBtn", class: "profile_updateBtn btn btn-primary btn-responsive col-sm-4" %>
                        <br/>
                        <br/>
                        	<%= link_to edit_user_registration_path do %>
                        	  <%= button_tag id: "chnageThisBtn", class: "profile_updateBtn btn btn-primary btn-responsive col-sm-9" do %> 
                                <div>
                                    <text class="col-sm-12">Change your PASSWORD<br/>(Pass Pattern)</text>
                                    <%= image_tag "patternLockIcon", class: "patUnlockIcon btn btn-responsive col-sm-4 col-sm-push-4 " %>
                                </div>
                              <% end %>
                              <%# button_tag "Change That", id: "chnageThatBtn", class: "profile_updateBtn btn btn-primary btn-responsive col-sm-4" %>
                        	<% end %>
                        	<div class="profileDetails col-sm-12">
                        		 <i class="glyphicon glyphicon-globe"></i> Your Username: <text> <%= @user.email.gsub('@mmc.ie', "") %> </text>
	                            <br />
	                            <i class="glyphicon glyphicon-time"></i> You joined 
	                            <text><%= time_ago_in_words(@user.created_at) %></text> ago
	                            <br />
	                            <i class="glyphicon glyphicon-gift"></i> You signed in <text><%= @user.sign_in_count %> </text> times
                                <br /><br />
                                <!--  <i class="glyphicon glyphicon-flash yellowFont"></i>
                                    <%# link_to "Enable fast login", user_enable_authy_path, class: "redFont ul" %>
                                 <i class="glyphicon glyphicon-flash yellowFont"></i> -->
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
	<div class="row" style="margin-left: 50px;">
        <div class="col-sm-4 col-sm-pull-2 col-md-pull-0">
            <button id="myBudgetsBtn" class="myBudgetsBtn btn btn-default orange-circle-button" href="">My<br />Budgets<br /></button>
            <div id="myBudgetsContainer">
                <div class="row" id="myBudgetsInfoBox" >
                    <h1 class="purpleFont col-sm-8">Your Budgets</h1>
                    <button id="myBudgetsHideBtn" class="col-xs-4 col-xs-push-4 col-sm-3 col-sm-push-0 myBudgetsHideBtn">Hide This</button>
                </div> 
                <div class="myBudgets">
                    <% @budgets.each_with_index do |budget, index| %>
                    <h2> <%= link_to "(#{(index + 1)}) " + budget.title, budget_path(budget) %> </h2> <br>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-sm-push-4 pushDown40">
            <button id="myGamesBtn" class="btn btn-default orange-circle-button" href="">My<br />Games / Modules<br /></button> 
        </div>
	</div>
</div>

<%= javascript_include_tag "profile" %>
<!-- Nessesary elements to copmplete page task (in order of usage) -->
<%# render 'shared/assistant', 
    :taskMode => true,
    :missedClickMode => false,
    :taskElems =>  ['myGamesBtn','booButton', 'myBudgetsBtn' ],
    :pageIntroduce => false %>

<style type="text/css">
    /* There is no task on this page s*/
    #pageIntroduceBtn{visibility: hidden;}
</style>

app/views/pages/store.html.erb
<!-- some sites for more learning games 
	 http://www.teachingmoney.co.uk/eurosite/euroindex.html 
	 http://www.edtech.ie/details.asp?id=16032&ptid=20124 - too expensive
	 https://www.gynzy.com/teachers/publishers/mathematics/  free
-->
<%= stylesheet_link_tag "store" %>
<%= stylesheet_link_tag "filterPanelReset" %>
<%= stylesheet_link_tag "filterPanelStyle" %>
 <header class="cd-header">
  <br><br>
    <h1>App store</h1>
  </header>


  <main id="filterPanelContainer" class="cd-main-content">
    <div class="cd-tab-filter-wrapper">
      <div class="cd-tab-filter">
        <ul class="cd-filters">
          <li class="placeholder"> 
            <a data-type="all" href="#0">All</a> <!-- selected option on mobile -->
          </li> 
          <li class="filter"><a class="selected" href="#0" data-type="all">All</a></li>
          <li class="filter" data-filter=".category-money"><a href="#0" data-type="category-money">Money</a></li>
          <li class="filter" data-filter=".category-budgets"><a href="#0" data-type="category-budgets">Budgets</a></li>
        </ul> <!-- cd-filters -->
      </div> <!-- cd-tab-filter -->
    </div> <!-- cd-tab-filter-wrapper -->

    <section class="cd-gallery">
      <ul>
        <!-- <li class="mix category-money check1 radio2 option3"><img src="" alt="Image 1"></li>
        <li class="mix category-budgets check2 radio2 option2"><img src="" alt="Image 2"></li>
 -->
     <% @iframe_games.each do |iframe_game| %>
     <%= link_to iframe_game do %>
 		<div class="col-md-6 gameDiv mix category-<%= "iframe_game.category here" %>">
			<div class="ssb-icon"><i class="fa fa-gamepad" aria-hidden="true"></i></div>
			<h2 class="ssb-title"><%= iframe_game.title %></h2>       
    	</div>

    	<!-- <li class="col-sm-6 videoElm mix category-<%= video.category %>">
          <div id="testBox" class="box text-center">
            <div class="video hidden">
              <iframe src="<%= video.link %>?version=3&enablejsapi=1" class="testVidClass" heightframeborder="0" allowfullscreen></iframe>
            </div>
            <div class="videoDescCard">
                <div class="incon-box">
                    <i class="fa <%= video.icon %>" aria-hidden="true"></i>
                </div>
                <h3 class="box-tittle"><%= video.title %> </h3>
                <p class="box-text"><%= video.description %></p>
            </div>
          </div>
      </li> -->
    <% end %>
<% end %>

 <%= render 'vending_machine' %>
     <!--    <li class="mix category-money check3 radio3 option1"><img src="" alt="Image 3"></li>
        <li class="mix category-money check3 radio2 option4"><img src="" alt="Image 4"></li>
        <li class="mix category-money check1 radio3 option2"><img src="" alt="Image 5"></li>
        <li class="mix category-budgets check2 radio3 option3"><img src="" alt="Image 6"></li>
        <li class="mix category-budgets check2 radio2 option1"><img src="" alt="Image 7"></li>
        <li class="mix category-money check1 radio3 option4"><img src="" alt="Image 8"></li>
        <li class="mix category-budgets check1 radio2 option3"><img src="" alt="Image 9"></li>
        <li class="mix category-money check3 radio2 option4"><img src="" alt="Image 10"></li>
        <li class="mix category-money check3 radio3 option2"><img src="" alt="Image 11"></li>
        <li class="mix category-budgets check1 radio3 option1"><img src="" alt="Image 12"></li> -->
        <li class="gap"></li>
        <li class="gap"></li>
        <li class="gap"></li>
      </ul>
      <div class="cd-fail-message">No results found</div>
    </section> <!-- cd-gallery -->

    <div class="cd-filter">
      <form>
        <div class="cd-filter-block">
          <h4>Check boxes</h4>

          <ul class="cd-filter-content cd-filters list">
            <li>
              <input class="filter" data-filter=".check1" type="checkbox" id="checkbox1">
                <label class="checkbox-label" for="checkbox1">Money</label>
            </li>

            <li>
              <input class="filter" data-filter=".check2" type="checkbox" id="checkbox2">
              <label class="checkbox-label" for="checkbox2">Budgets</label>
            </li>

            <li>
              <input class="filter" data-filter=".check3" type="checkbox" id="checkbox3">
              <label class="checkbox-label" for="checkbox3">Option 3 here</label>
            </li>
          </ul> <!-- cd-filter-content -->
        </div> <!-- cd-filter-block -->

        <div class="cd-filter-block">
          <h4>Select</h4>
          
          <div class="cd-filter-content">
            <div class="cd-select cd-filters">
              <select class="filter" name="selectThis" id="selectThis">
                <option value="">Choose an option</option>
                <option value=".option1">Option 1</option>
                <option value=".option2">Option 2</option>
                <option value=".option3">Option 3</option>
                <option value=".option4">Option 4</option>
              </select>
            </div> <!-- cd-select -->
          </div> <!-- cd-filter-content -->
        </div> <!-- cd-filter-block -->
      </form>

      <a href="#0" class="cd-close">Close</a>
    </div> <!-- cd-filter -->

  <a href="#0" class="cd-filter-trigger">Filters</a> 
  </main> <!-- cd-main-content -->
<%= javascript_include_tag "jquery.mixitup.min" %>
<%= javascript_include_tag "filterPanelMain" %>   





app/views/pages/ux_testing_view.html.erb
<%= %>
<div style="margin-left: 100px;">
	<% @users.each do |u| %>
		<% @theBudgets = u.budgets %>
		<div class="col-md-3" style="border:1px solid #7b69eb; margin: 12px;">
			<h1><u><%= u.email %></u></h1>
			<h3>Budgets <%= (@theBudgets.count) %>:</h3>
			<% @theBudgets.each_with_index do |b, index| %>
				<h4>
					[ <%= (index + 1) %> ]
					<%= link_to b.title, b %>
				</h4>
			<% end %>
		</div>
	<% end %>
</div>	